# Generated by Django 4.1.5 on 2023-02-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_balanceARS",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_balanceUSD",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_balanceEUR",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_balanceTRANSFER",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_balanceCREDITO",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_balanceDEBITO",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of transaction",
                        max_digits=15,
                    ),
                ),
                (
                    "operation_mode",
                    models.CharField(
                        choices=[("Ingreso", "Ingreso"), ("Egreso", "Egreso")],
                        help_text="Operation mode",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="description of the operation",
                        max_length=500,
                    ),
                ),
                (
                    "money_type",
                    models.CharField(
                        choices=[
                            ("PESO", "PESO"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRANSFER", "TRANSFER"),
                            ("CREDITO", "CREDITO"),
                            ("DEBITO", "DEBITO"),
                        ],
                        help_text="money type",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cashregister",
                    models.ForeignKey(
                        help_text="Cash register",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_cash",
                        to="cashregister.cashregister",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        help_text="Usuario Operator",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="user_cash",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
