# Generated by Django 4.1.2 on 2023-02-26 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
