# Generated by Django 4.1.5 on 2023-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashregister", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceARS",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceCREDITO",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceDEBITO",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceEUR",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceTRANSFER",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="total_balanceUSD",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="movement",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Amount of transaction", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="operation_mode",
            field=models.CharField(
                choices=[("Ingreso", "Ingreso"), ("Egreso", "Egreso")],
                help_text="Operation mode",
                max_length=10,
            ),
        ),
    ]
