# Generated by Django 4.1.7 on 2023-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_comission_detail_alter_comission_type'),
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(default=None, help_text='Usuario Operator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_movements', to='adviser.adviser'),
        ),
    ]
