# Generated by Django 4.1.5 on 2023-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashregister", "0003_alter_movement_money_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashregister",
            name="total_balanceCREDITO",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_balanceDEBITO",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
