# Generated by Django 4.1.2 on 2023-02-24 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister', '0004_alter_cashregister_total_balancecredito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(default=None, help_text='Usuario Operator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
