# Generated by Django 4.1.7 on 2023-03-23 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashregister', '0001_initial'),
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(choices=[('REGISTRO', 'REGISTRO'), ('COBRO', 'COBRO'), ('VENTA', 'VENTA')], max_length=20, null=True)),
                ('money_type', models.CharField(choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFERENCIA')], default='PESOS', max_length=20, null=True)),
                ('last_up', models.DateTimeField(default=datetime.datetime.now)),
                ('detail', models.TextField(blank=True, help_text='Detalle de la operacion', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.adviser')),
                ('mov', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
