# Generated by Django 4.1.5 on 2023-03-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_credit',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Interes general para creditos', max_digits=5),
        ),
        migrations.AddField(
            model_name='interest',
            name='porcentage_daily_interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, help_text='Porcentaje de interes por retraso diario', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='daily_interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, help_text='Disminucion de puntos por retraso diario', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='points_score_refinancing',
            field=models.DecimalField(blank=True, decimal_places=2, default=80, help_text='Puntos por refinanciacion pagada', max_digits=5, null=True),
        ),
    ]
