# Generated by Django 4.1.5 on 2023-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="color",
            field=models.CharField(
                blank=True, help_text="Color de la nota", max_length=10, null=True
            ),
        ),
    ]
