# Generated by Django 4.1.7 on 2023-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_comission_detail_alter_comission_type'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='Notas de Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_notes', to='adviser.adviser'),
        ),
    ]
