<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-04-04 19:13
=======
<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-04-03 16:56
=======
# Generated by Django 4.1.5 on 2023-04-04 18:18
>>>>>>> 33525e74 (hotfixs)
>>>>>>> 2df94caedcc402d29d56ad2bb3d025dd2d4f2705

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cashregister', '0001_initial'),
        ('credit', '0001_initial'),
        ('commissions', '0001_initial'),
        ('adviser', '0001_initial'),
=======
<<<<<<< HEAD
        ("commissions", "__first__"),
        ("adviser", "0001_initial"),
        ("cashregister", "__first__"),
        ("credit", "0001_initial"),
=======
        ('adviser', '0001_initial'),
        ('credit', '0001_initial'),
        ('commissions', '0001_initial'),
        ('cashregister', '0001_initial'),
>>>>>>> 33525e74 (hotfixs)
>>>>>>> 2df94caedcc402d29d56ad2bb3d025dd2d4f2705
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Payment',
=======
<<<<<<< HEAD
            name="Payment",
>>>>>>> 2df94caedcc402d29d56ad2bb3d025dd2d4f2705
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto de Pago', max_digits=15)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFER'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], help_text='Metodo de Pago', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.adviser')),
                ('commission_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commission')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.installment')),
                ('installment_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.installmentrefinancing')),
                ('mov', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
            options={
<<<<<<< HEAD
                'ordering': ['-created_at'],
=======
                "ordering": ["-created_at"],
=======
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto de Pago', max_digits=15)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFER'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], help_text='Metodo de Pago', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.adviser')),
                ('commission_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commission')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.installment')),
                ('installment_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.installmentrefinancing')),
                ('mov', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
            options={
                'ordering': ['-created_at'],
>>>>>>> 33525e74 (hotfixs)
>>>>>>> 2df94caedcc402d29d56ad2bb3d025dd2d4f2705
            },
        ),
    ]
