# Generated by Django 4.1.5 on 2023-03-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="credit.installment",
            ),
            preserve_default=False,
        ),
    ]
