# Generated by Django 4.2 on 2025-04-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='partial',
            field=models.BooleanField(default=False, help_text='Pago Parcial'),
        ),
    ]
