# Generated by Django 4.1.7 on 2023-03-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_date',
            new_name='payment_date',
        ),
    ]
