# Generated by Django 4.1.5 on 2023-02-27 23:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adviser", "0002_remove_comission_commission_charged_to"),
        ("credit", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="detaill",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refinancing",
        ),
        migrations.AddField(
            model_name="payment",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adviser.adviser",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(default=None, help_text="Monto de Pago"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, help_text="Fecha de Pago"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("PESOS", "PESOS"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRANSFER", "TRANSFER"),
                    ("CREDITO", "CREDITO"),
                    ("DEBITO", "DEBITO"),
                ],
                default=0,
                help_text="Metodo de Pago",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="credit.installment",
            ),
        ),
    ]
