# Generated by Django 4.1.5 on 2023-02-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0010_credit_is_active_alter_installment_credit_and_more"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="installment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Cuota que se esta pagando",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="installment_pay",
                to="credit.installment",
            ),
        ),
    ]
