# Generated by Django 4.2 on 2025-04-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checked_discount',
            field=models.BooleanField(default=False, help_text='Descuento chequeado'),
        ),
    ]
