# Generated by Django 4.1.5 on 2023-02-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0010_credit_is_active_alter_installment_credit_and_more"),
        ("payment", "0002_alter_payment_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refinancing",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Refinanciacion que se esta pagando",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="refinancing_pay",
                to="credit.installmentrefinancing",
            ),
        ),
    ]
