# Generated by Django 4.1.2 on 2023-02-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_detaill_remove_payment_refinancing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de Pago', max_digits=15),
        ),
    ]
