# Generated by Django 4.1.7 on 2023-03-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_refinancing_lastup'),
        ('payment', '0002_rename_paid_date_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.installmentrefinancing'),
        ),
    ]
