# Generated by Django 4.1.7 on 2023-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paid_date_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['created_at']},
        ),
    ]
