# Generated by Django 4.2 on 2025-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_checked_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto descontado', max_digits=15),
        ),
    ]
