# Generated by Django 4.1.5 on 2023-03-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
        ("payment", "0003_alter_payment_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="credit.installmentrefinancing",
            ),
        ),
    ]
