# Generated by Django 4.1.7 on 2023-03-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
