# Generated by Django 4.1.7 on 2023-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_comission_detail_alter_comission_type'),
        ('payment', '0006_alter_payment_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.adviser'),
        ),
    ]
