# Generated by Django 4.1.5 on 2023-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='is_prueba',
            field=models.BooleanField(default=False),
        ),
    ]
