# Generated by Django 4.1.5 on 2023-04-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantor', '0002_alter_guarantor_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='credit',
        ),
    ]
