# Generated by Django 4.1.5 on 2023-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantor', '0002_guarantor_is_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='is_prueba_1',
            field=models.BooleanField(default=False),
        ),
    ]
