# Generated by Django 4.1.5 on 2023-02-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=50, null=True
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Celular"), ("F", "Fijo"), ("A", "Alternativo")],
                        help_text="Type of phone",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(help_text="First name", max_length=50)),
                ("last_name", models.CharField(help_text="Last name", max_length=50)),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "civil_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Soltero"),
                            ("C", "Casado"),
                            ("V", "Viudo"),
                            ("D", "Divorciado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dni", models.PositiveIntegerField(help_text="dni number")),
                ("profession", models.CharField(help_text="Profession", max_length=50)),
                ("address", models.CharField(help_text="Address", max_length=250)),
                (
                    "job_address",
                    models.CharField(help_text="Job address", max_length=250),
                ),
                ("phone_numbers", models.ManyToManyField(to="clients.phonenumber")),
            ],
        ),
    ]
