# Generated by Django 4.1.5 on 2023-03-31 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.ImageField(blank=True, null=True, upload_to='salary_checks/')),
                ('date_admission', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de admision')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='salary_check',
            field=models.ForeignKey(blank=True, default=None, help_text='Recibo de sueldo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.salary_check'),
        ),
    ]
