# Generated by Django 4.1.5 on 2023-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number",
                max_length=50,
                null=True,
                verbose_name="Numero de Telefono",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_type",
            field=models.CharField(
                choices=[("C", "Celular"), ("F", "Fijo"), ("A", "Alternativo")],
                help_text="Type of phone",
                max_length=20,
                verbose_name="Tipo de Telefono",
            ),
        ),
    ]
