# Generated by Django 4.1.5 on 2023-03-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_check',
            name='client',
            field=models.ForeignKey(blank=True, default=None, help_text='Recibo de sueldo', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
