# Generated by Django 4.1.2 on 2023-02-24 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adviser',
            field=models.ForeignKey(blank=True, default=None, help_text='Clientes del usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
