# Generated by Django 4.1.5 on 2023-04-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_pay_stub',
        ),
    ]
