# Generated by Django 4.1.5 on 2023-02-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adviser", "0002_remove_comission_commission_charged_to"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Clientes del usuario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adviser.adviser",
            ),
        ),
    ]
