# Generated by Django 4.1.5 on 2023-03-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_leagls',
            new_name='is_legals',
        ),
    ]
