# Generated by Django 4.1.7 on 2023-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=10, verbose_name='Estado civil'),
        ),
    ]
