# Generated by Django 4.1.5 on 2023-03-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_salary_check_client_salary_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_check',
            name='salary',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='salary_checks/'),
        ),
    ]
