# Generated by Django 4.1.5 on 2023-03-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_is_leagls_client_is_legals'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_guarantor',
            field=models.BooleanField(default=False),
        ),
    ]
