# Generated by Django 4.1.5 on 2023-03-31 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_salary_check_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_check',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary_check',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
