# Generated by Django 4.1.5 on 2023-03-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_salary_check_created_at_salary_check_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_check',
            name='date_admission',
        ),
    ]
