# Generated by Django 4.1.5 on 2023-03-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_salary_check_date_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='salary_check',
        ),
        migrations.AddField(
            model_name='salary_check',
            name='client',
            field=models.ForeignKey(blank=True, default=None, help_text='Recibo de sueldo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
