# Generated by Django 4.1.2 on 2023-02-24 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid_credit', models.BooleanField(default=False, help_text='El credito esta pagado')),
                ('is_old_credit', models.BooleanField(default=False, help_text='Es un credito antiguo')),
                ('condition', models.CharField(choices=[('Pagado', 'Pagado'), ('A Tiempo', 'A Tiempo'), ('Legales', 'Legales')], default='A Tiempo', max_length=15)),
                ('credit_interest', models.PositiveIntegerField(default=40, help_text='Intereses de credito')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del Credito', max_digits=15)),
                ('credit_repayment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto de Devolucion del Credito', max_digits=15)),
                ('installment_num', models.PositiveIntegerField(default=1, help_text='Numeros de Cuotas', null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Fecha de Finalizacion del Credito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, default=None, help_text='Cliente del Credito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_credits', to='clients.client')),
                ('mov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_caduced_installment', models.BooleanField(default=False, help_text='La cuota esta vencida')),
                ('is_paid_installment', models.BooleanField(default=False, help_text='La cuota esta pagada')),
                ('is_refinancing_installment', models.BooleanField(default=False, help_text='La cuota fue refinanciada')),
                ('installment_number', models.PositiveSmallIntegerField(help_text='Numero de cuota del credito')),
                ('acc_int', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('condition', models.CharField(choices=[('Pagada', 'Pagada'), ('Refinanciada', 'Refinanciada'), ('Vencida', 'Vencida'), ('A Tiempo', 'A Tiempo')], default='A Tiempo', max_length=15)),
                ('amount_installment', models.DecimalField(decimal_places=2, help_text='Monto de la cuota', max_digits=15)),
                ('payment_date', models.DateField(help_text='Fecha de pago de la cuota')),
                ('lastup', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.ForeignKey(help_text='Credito de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='credit.credit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid_refinancing', models.BooleanField(default=False, help_text='La refinanciacion esta pagada')),
                ('refinancing_interest', models.PositiveIntegerField(default=48, help_text='Intereses de la refinanciacion')),
                ('amount_refinancing', models.DecimalField(decimal_places=2, help_text='Monto a refinanciar', max_digits=15)),
                ('refinancing_repayment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto de Devolver de la Refinanciacion', max_digits=15)),
                ('installment_num_refinancing', models.PositiveIntegerField(default=1, help_text='Numeros de Cuotas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment', models.OneToOneField(blank=True, default=None, help_text='Cuota de la Refinanciacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refinancing', to='credit.installment')),
                ('mov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentRefinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_caduced_installment', models.BooleanField(default=False, help_text='La cuota esta vencida')),
                ('is_paid_installment', models.BooleanField(default=False, help_text='La cuota esta pagada')),
                ('condition', models.CharField(choices=[('Pagado', 'Pagado'), ('A Tiempo', 'A Tiempo'), ('Legales', 'Legales')], default='A Tiempo', max_length=15)),
                ('installment_number', models.PositiveSmallIntegerField(help_text='Numero de cuota de la refinanciacion')),
                ('amount_installment', models.DecimalField(decimal_places=2, help_text='Monto de la cuota de refinanciacion', max_digits=15)),
                ('payment_date', models.DateField(help_text='Fecha de pago de la cuota de refinanciacion')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Inicio')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refinancing', models.ForeignKey(help_text='Refinanciacion de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installment_refinancing', to='credit.refinancing')),
            ],
        ),
    ]
