# Generated by Django 4.1.5 on 2023-02-14 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_paid_credit",
                    models.BooleanField(
                        default=False, help_text="El credito esta pagado"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto del Credito", max_digits=15
                    ),
                ),
                (
                    "number_installment",
                    models.PositiveIntegerField(
                        default=1, help_text="Numeros de Cuotas", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Usuario del Credito",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="user_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_caduced_installment",
                    models.BooleanField(
                        default=False, help_text="La cuota esta vencida"
                    ),
                ),
                (
                    "is_paid_installment",
                    models.BooleanField(
                        default=False, help_text="La cuota esta pagada"
                    ),
                ),
                (
                    "is_refinancing_installment",
                    models.BooleanField(
                        default=False, help_text="La cuota fue refinanciada"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveSmallIntegerField(help_text="Numero de la cuota"),
                ),
                (
                    "amount_installment",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto de la cuota", max_digits=15
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Fecha de pago de la cuota"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit",
                    models.ForeignKey(
                        help_text="Credito de la cuota",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit",
                        to="credit.credit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refinancing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_caduced_refinancing",
                    models.BooleanField(
                        default=False,
                        help_text="La cuota de refinanciacion esta vencida",
                    ),
                ),
                (
                    "is_paid_refinancing",
                    models.BooleanField(
                        default=False, help_text="La cuota esta pagada"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installment",
                    models.OneToOneField(
                        help_text="Cuota de la refinancioacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refinement",
                        to="credit.installment",
                    ),
                ),
            ],
        ),
    ]
