# Generated by Django 4.1.5 on 2023-02-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="credit_interest",
            field=models.PositiveIntegerField(
                default=0, help_text="Intereses de credito"
            ),
        ),
    ]
