# Generated by Django 4.1.2 on 2023-02-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='mov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashregister.movement'),
        ),
        migrations.AlterField(
            model_name='refinancing',
            name='mov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashregister.movement'),
        ),
    ]
