# Generated by Django 4.1.7 on 2023-02-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['created_at']},
        ),
    ]
