# Generated by Django 4.1.5 on 2023-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_guarantor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='condition',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('A Tiempo', 'A Tiempo')], default='A Tiempo', max_length=15),
        ),
    ]
