# Generated by Django 4.1.5 on 2023-02-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="end_date",
            field=models.DateTimeField(
                null=True, verbose_name="Fecha de Finalizacion del Credito"
            ),
        ),
    ]
