# Generated by Django 4.1.7 on 2023-03-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refinancing',
            name='mov',
        ),
    ]
