# Generated by Django 4.1.2 on 2023-02-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='installmentrefinancing',
            old_name='due_date',
            new_name='end_date',
        ),
    ]
