# Generated by Django 4.1.5 on 2023-04-01 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha de Inicio",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="installmentrefinancing",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Inicio"
            ),
        ),
        migrations.AlterField(
            model_name="refinancing",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
