# Generated by Django 4.1.7 on 2023-03-06 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refinancing',
            old_name='refinancing_interest',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_date',
            field=models.DateTimeField(default=None, help_text='Fecha de Pago', null=True),
        ),
        migrations.AddField(
            model_name='installmentrefinancing',
            name='daily_interests',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intereses diarios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='installmentrefinancing',
            name='lastup',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='refinancing',
            name='lastup',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='refinancing',
            name='payment_date',
            field=models.DateTimeField(default=None, help_text='Fecha de Pago', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='credit',
            field=models.ForeignKey(help_text='Credito de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='condition',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('A Tiempo', 'A Tiempo'), ('Legales', 'Legales')], default='A Tiempo', max_length=15),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='refinancing',
            field=models.ForeignKey(help_text='Refinanciacion de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit.refinancing'),
        ),
        migrations.AlterField(
            model_name='refinancing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
