# Generated by Django 4.2 on 2025-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='original_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
