# Generated by Django 4.1.2 on 2023-02-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='mov',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='acc_int',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='installment',
            name='daily_interests',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intereses diarios', max_digits=20, null=True),
        ),
    ]
