# Generated by Django 4.1.5 on 2023-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='has_pay_stub',
            field=models.BooleanField(blank=True, default=False, verbose_name='Recibo de sueldo'),
        ),
    ]
