# Generated by Django 4.1.5 on 2023-03-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refinancing",
            name="credit",
            field=models.ForeignKey(
                blank=True,
                help_text="Credito de la cuota",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refinancing",
                to="credit.credit",
            ),
        ),
    ]
