# Generated by Django 4.1.5 on 2023-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0002_credit_credit_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="credit_interest",
            field=models.PositiveIntegerField(
                default=40, help_text="Intereses de credito"
            ),
        ),
    ]
