# Generated by Django 4.1.5 on 2023-03-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_is_guarantor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='is_guarantor',
        ),
    ]
