# Generated by Django 4.1.2 on 2023-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_rename_due_date_installment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFERENCIA')], max_length=15, null=True),
        ),
    ]
