# Generated by Django 4.1.2 on 2023-02-24 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_alter_installment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Inicio'),
        ),
    ]
