# Generated by Django 4.1.5 on 2023-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "credit",
            "0002_alter_credit_start_date_alter_installment_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="installment",
            name="end_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="installmentrefinancing",
            name="end_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de Vencimiento"
            ),
        ),
    ]
