# Generated by Django 4.1.7 on 2023-02-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
        ('credit', '0002_remove_credit_mov_remove_installment_acc_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='mov',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashregister.movement'),
        ),
    ]
