# Generated by Django 4.1.5 on 2025-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_installment_original_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentrefinancing',
            name='original_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
