# Generated by Django 4.1.7 on 2023-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_rename_refinancing_interest_refinancing_interest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='installmentrefinancing',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='refinancing',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='installment',
            name='lastup',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='lastup',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='refinancing',
            name='lastup',
            field=models.DateField(null=True),
        ),
    ]
