# Generated by Django 4.1.2 on 2023-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_installment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='condition',
            field=models.CharField(blank=True, choices=[('Pagada', 'Pagada'), ('Refinanciada', 'Refinanciada'), ('Vencida', 'Vencida'), ('A Tiempo', 'A Tiempo')], default='A Tiempo', max_length=15),
        ),
    ]
