# Generated by Django 4.1.7 on 2023-03-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credit_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='is_paid_credit',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='refinancing',
            old_name='is_paid_refinancing',
            new_name='is_paid',
        ),
    ]
