# Generated by Django 4.1.7 on 2023-03-04 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_credit_payment_date_installment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinancing',
            name='lastup',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
