# Generated by Django 4.1.5 on 2023-02-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0003_alter_credit_credit_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="credit_repayment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto de Devolucion del Credito",
                max_digits=15,
            ),
            preserve_default=False,
        ),
    ]
