# Generated by Django 4.1.5 on 2023-03-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_guarantor'),
        ('credit', '0003_remove_credit_is_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='guarantor',
            field=models.ForeignKey(blank=True, default=None, help_text='Garante del Credito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='clients.client'),
        ),
    ]
