# Generated by Django 4.1.5 on 2023-02-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_created_at_client_updated_at"),
        ("credit", "0004_credit_credit_repayment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="user",
        ),
        migrations.AddField(
            model_name="credit",
            name="client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cliente del Credito",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="client_credits",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="refinancing",
            name="refinancing_interest",
            field=models.PositiveIntegerField(
                default=40, help_text="Intereses de la refinanciacion"
            ),
        ),
    ]
