# Generated by Django 4.1.7 on 2023-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_refinancing_lastup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinancing',
            name='payment_date',
            field=models.DateTimeField(default=None, help_text='Fecha de Pago', null=True),
        ),
    ]
