# Generated by Django 4.1.2 on 2023-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_installment_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='condition',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('Refinanciada', 'Refinanciada'), ('Vencida', 'Vencida'), ('A Tiempo', 'A Tiempo')], default='A Tiempo', max_length=15),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFERENCIA')], max_length=15, null=True),
        ),
    ]
