# Generated by Django 4.1.2 on 2023-02-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_installment_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='amount_installment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='installmentrefinancing',
            old_name='amount_installment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='refinancing',
            old_name='amount_refinancing',
            new_name='amount',
        ),
    ]
