# Generated by Django 4.1.7 on 2023-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_credit_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinancing',
            name='lastup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
