# Generated by Django 4.1.5 on 2023-03-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_remove_credit_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinancing',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Finalizacion de Refinanciacion'),
        ),
    ]
