# Generated by Django 4.1.2 on 2023-03-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_refinancing_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment_date',
            field=models.DateTimeField(default=None, help_text='Fecha de Pago', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_date',
            field=models.DateTimeField(default=None, help_text='Fecha de Pago', null=True),
        ),
    ]
