# Generated by Django 4.1.5 on 2023-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0005_remove_credit_user_credit_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="credit_repayment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto de Devolucion del Credito",
                max_digits=15,
            ),
        ),
    ]
