# Generated by Django 4.1.5 on 2023-03-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_refinancing_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='installmentrefinancing',
            name='start_date',
        ),
    ]
