# Generated by Django 4.1.2 on 2023-03-06 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_alter_credit_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refinancing',
            old_name='refinancing_interest',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='installmentrefinancing',
            name='daily_interests',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intereses diarios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='installmentrefinancing',
            name='lastup',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
