# Generated by Django 4.1.7 on 2023-03-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_alter_refinancing_lastup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refinancing',
            name='installment',
        ),
        migrations.AddField(
            model_name='installment',
            name='refinance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.refinancing'),
        ),
    ]
