# Generated by Django 4.1.5 on 2023-02-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0007_alter_credit_credit_repayment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refinancing",
            name="is_caduced_refinancing",
        ),
        migrations.AddField(
            model_name="refinancing",
            name="amount_refinancing",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto a refinanciar",
                max_digits=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refinancing",
            name="number_installment_refinancing",
            field=models.PositiveIntegerField(
                default=1, help_text="Numeros de Cuotas", null=True
            ),
        ),
        migrations.AddField(
            model_name="refinancing",
            name="refinancing_repayment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Monto de Devolver de la Refinanciacion",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="installment_number",
            field=models.PositiveSmallIntegerField(
                help_text="Numero de cuota del credito"
            ),
        ),
        migrations.AlterField(
            model_name="refinancing",
            name="installment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Cuota de la Refinanciacion",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="installment_refinancing",
                to="credit.installment",
            ),
        ),
        migrations.AlterField(
            model_name="refinancing",
            name="is_paid_refinancing",
            field=models.BooleanField(
                default=False, help_text="La refinanciacion esta pagada"
            ),
        ),
        migrations.CreateModel(
            name="InstallmentRefinancing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_caduced_installment",
                    models.BooleanField(
                        default=False, help_text="La cuota esta vencida"
                    ),
                ),
                (
                    "is_paid_installment",
                    models.BooleanField(
                        default=False, help_text="La cuota esta pagada"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveSmallIntegerField(
                        help_text="Numero de cuota de la refinanciacion"
                    ),
                ),
                (
                    "amount_installment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto de la cuota de refinanciacion",
                        max_digits=15,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="Fecha de pago de la cuota de refinanciacion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "refinancing",
                    models.ForeignKey(
                        help_text="Refinanciacion de la cuota",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refinancing",
                        to="credit.refinancing",
                    ),
                ),
            ],
        ),
    ]
