# Generated by Django 4.1.2 on 2023-03-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_rename_refinancing_interest_refinancing_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='credit',
            field=models.ForeignKey(help_text='Credito de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de pago de la cuota de refinanciacion', null=True),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='refinancing',
            field=models.ForeignKey(help_text='Refinanciacion de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit.refinancing'),
        ),
    ]
