# Generated by Django 4.1.7 on 2023-03-07 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_remove_refinancing_installment_installment_refinance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='refinance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_ref', to='credit.refinancing'),
        ),
    ]
