# Generated by Django 4.1.5 on 2023-03-30 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_remove_installment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('48.00'), help_text='Intereses de credito', max_digits=15),
        ),
    ]
