# Generated by Django 4.1.5 on 2023-02-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0008_remove_refinancing_is_caduced_refinancing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refinancing",
            name="installment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Cuota de la Refinanciacion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_refinancing",
                to="credit.installment",
            ),
        ),
    ]
