# Generated by Django 4.1.2 on 2023-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_alter_installment_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
