# Generated by Django 4.1.5 on 2023-02-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0009_alter_refinancing_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="installment",
            name="credit",
            field=models.ForeignKey(
                help_text="Credito de la cuota",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment",
                to="credit.credit",
            ),
        ),
        migrations.AlterField(
            model_name="installmentrefinancing",
            name="refinancing",
            field=models.ForeignKey(
                help_text="Refinanciacion de la cuota",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_refinancing",
                to="credit.refinancing",
            ),
        ),
        migrations.AlterField(
            model_name="refinancing",
            name="installment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Cuota de la Refinanciacion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refinancing",
                to="credit.installment",
            ),
        ),
    ]
