# Generated by Django 4.1.5 on 2023-03-30 14:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_installment_porcentage_daily_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentrefinancing',
            name='porcentage_daily_interests',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Intereses diarios', max_digits=20, null=True),
        ),
    ]
