# Generated by Django 4.1.5 on 2023-02-18 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0010_credit_is_active_alter_installment_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="Cuando fue otorgado el credito",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="is_old_credit",
            field=models.BooleanField(default=False, help_text="Es un credito antiguo"),
        ),
    ]
