# Generated by Django 4.1.2 on 2023-03-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_alter_installmentrefinancing_refinancing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='refinancing',
            field=models.ForeignKey(help_text='Refinanciacion de la cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credit.refinancing'),
        ),
    ]
