# Generated by Django 4.1.2 on 2023-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_alter_installmentrefinancing_refinancing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
