# Generated by Django 4.1.5 on 2023-03-30 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_remove_installment_porcentage_daily_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='porcentage_daily_interests',
        ),
        migrations.AddField(
            model_name='installment',
            name='porcentage_daily_interests',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Intereses diarios', max_digits=20, null=True),
        ),
    ]
