# Generated by Django 4.1.5 on 2023-03-30 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_remove_credit_porcentage_daily_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='installmentrefinancing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Inicio'),
        ),
    ]
