# Generated by Django 4.1.2 on 2023-03-06 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_alter_credit_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinancing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
