# Generated by Django 4.1.5 on 2023-03-30 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_installment_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinancing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
