# Generated by Django 4.1.2 on 2023-03-06 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_alter_refinancing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installmentrefinancing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
