# Generated by Django 4.1.2 on 2023-03-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(help_text='Articulo', max_length=50, verbose_name='Articulo')),
                ('purchase_papers', models.BooleanField(blank=True, default=False, help_text='Papeles de compra', verbose_name='Papeles de compra')),
                ('brand', models.CharField(help_text='Marca', max_length=50, verbose_name='Marca')),
                ('model', models.CharField(help_text='Modelo', max_length=50, verbose_name='Modelo')),
                ('accessories', models.CharField(help_text='Accesorios', max_length=50, verbose_name='Accesorios')),
                ('state', models.CharField(blank=True, choices=[('NUEVO', 'NUEVO'), ('USADO:COMO NUEVO', 'USADO:COMO NUEVO'), ('USADO:MUY BUENO', 'USADO:MUY BUENO'), ('USADO:BUENO', 'USADO:BUENO'), ('USADO:ACEPTABLE', 'USADO:ACEPTABLE'), ('USADO:REACONDICIONADO', 'USADO:REACONDICIONADO'), ('USADO:MUCHO USO', 'USADO:MUCHO USO')], max_length=30, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.ForeignKey(blank=True, default=None, help_text='Empeño del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_clients', to='credit.credit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
