# Generated by Django 4.1.2 on 2023-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='article',
            field=models.CharField(help_text='Articulo', max_length=50, verbose_name='Articulo'),
        ),
    ]
