# Generated by Django 4.1.7 on 2023-03-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_warranty_is_selled_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='detail',
            field=models.CharField(blank=True, help_text='Observaciones del articulo', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='detail',
            field=models.CharField(blank=True, help_text='Observaciones del articulo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell', to='warranty.warranty'),
        ),
    ]
