# Generated by Django 4.1.7 on 2023-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_sell_detail_warranty_detail_alter_sell_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='detail',
            field=models.TextField(blank=True, help_text='Observaciones del articulo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFERENCIA'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], default=('PESOS', 'PESOS'), max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='detail',
            field=models.TextField(blank=True, help_text='Observaciones del articulo', max_length=150, null=True),
        ),
    ]
