# Generated by Django 4.1.7 on 2023-03-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_comission_interest_alter_comission_type'),
        ('warranty', '0004_alter_sell_detail_alter_sell_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adviser.comission'),
        ),
    ]
