# Generated by Django 4.1.7 on 2023-03-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_comission_interest_alter_comission_type'),
        ('warranty', '0006_sell_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.comission'),
        ),
    ]
