# Generated by Django 4.1.7 on 2023-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_remove_warranty_is_selled_alter_warranty_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='is_selled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='state',
            field=models.CharField(blank=True, choices=[('NUEVO', 'NUEVO'), ('USADO:COMO NUEVO', 'USADO:COMO NUEVO'), ('USADO:MUY BUENO', 'USADO:MUY BUENO'), ('USADO:BUENO', 'USADO:BUENO'), ('USADO:ACEPTABLE', 'USADO:ACEPTABLE'), ('USADO:REACONDICIONADO', 'USADO:REACONDICIONADO'), ('USADO:MUCHO USO', 'USADO:MUCHO USO')], max_length=30, verbose_name='Estado'),
        ),
    ]
