# Generated by Django 4.1.7 on 2023-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='detail',
            field=models.TextField(blank=True, help_text='Detalle de la operacion', max_length=100, null=True),
        ),
    ]
