# Generated by Django 4.1.5 on 2023-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adviser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adviser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar/"),
        ),
    ]
