# Generated by Django 4.1.7 on 2023-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='comission',
            name='type',
            field=models.CharField(choices=[('REGISTRO', 'REGISTRO'), ('COBRO', 'COBRO'), ('VENTA', 'VENTA')], max_length=20, null=True),
        ),
    ]
