# Generated by Django 4.1.7 on 2023-03-03 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='adviser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
