# Generated by Django 4.1.5 on 2023-03-28 16:25

import adviser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adviser", "0002_adviser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adviser",
            name="user",
            field=models.OneToOneField(
                default=adviser.models.default_avatar,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adviser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
