# Generated by Django 4.1.7 on 2023-03-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_comission_interest_alter_comission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comission',
            old_name='create_date',
            new_name='last_up',
        ),
    ]
