# Generated by Django 4.1.2 on 2023-03-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0003_rename_create_date_comission_last_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='operacion_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
