# Generated by Django 4.1.7 on 2023-02-22 23:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0002_alter_cashregister_total_balancears_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adviser', '0003_alter_adviser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('c_type', models.CharField(choices=[('REGISTRO', 'REGISTRO'), ('COBRO', 'COBRO')], default='Registro', max_length=20, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mov', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement')),
            ],
        ),
    ]
