# Generated by Django 4.1.2 on 2023-02-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0004_remove_comission_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='type',
            field=models.CharField(choices=[('REGISTRO', 'REGISTRO'), ('COBRO', 'COBRO')], default='REGISTRO', max_length=20, null=True),
        ),
    ]
