# Generated by Django 4.1.2 on 2023-03-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0004_comission_operacion_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comission',
            old_name='operacion_amount',
            new_name='original_amount',
        ),
    ]
