# Generated by Django 4.1.2 on 2023-02-24 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adviser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister', '0005_alter_movement_user'),
        ('adviser', '0004_comission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comission',
            old_name='c_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='comission',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comission',
            name='commission_charged_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='comission',
            name='money_type',
            field=models.CharField(choices=[('PESOS', 'PESOS'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRANSFER', 'TRANSFERENCIA')], default=('PESOS', 'PESOS'), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comission',
            name='adviser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comission',
            name='mov',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashregister.movement'),
        ),
    ]
