# Generated by Django 4.1.7 on 2023-03-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_comission_detail_alter_comission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comission',
            old_name='checked',
            new_name='is_paid',
        ),
    ]
