# Generated by Django 4.1.2 on 2023-02-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adviser'),
        ('adviser', '0007_alter_comission_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='commission_charged_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
