# Generated by Django 4.1.2 on 2023-02-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister', '0005_alter_movement_user'),
        ('adviser', '0011_alter_comission_commission_charged_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comission',
            name='mov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.movement'),
        ),
    ]
